# Generated by Django 4.2.5 on 2023-12-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Data15T',
            fields=[
                ('rawdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_display.rawdata')),
            ],
            bases=('data_display.rawdata',),
        ),
        migrations.CreateModel(
            name='Data1D',
            fields=[
                ('rawdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_display.rawdata')),
            ],
            bases=('data_display.rawdata',),
        ),
        migrations.CreateModel(
            name='Data60T',
            fields=[
                ('rawdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_display.rawdata')),
            ],
            bases=('data_display.rawdata',),
        ),
    ]
